### ISSUE TITLE
Pydantic versions?

### ISSUE THREAD

**Issue by bmschwa** [formkiq/formkiq-client-sdk-python#2]
Hey @mfriesen, what versions of pydantic did you use?   The requirements mentions `pydantic>2.0`; I had a deprecation error with 2..6.3 and an assertion error when using 2.0.   ... Rather than guess,  thought I'd ask.

**Comment by mfriesen** [comment]
The python library is using the OpenAPI python generator (https://github.com/openapi-generators/openapi-python-client)

According to https://github.com/openapi-generators/openapi-python-client/blob/main/pyproject.toml it's using  "pydantic>=2.1.1,<3.0.0",

Hope that helps.
